LongName: University of Texas at El Paso Research and Academic Data Center
Description: University of Texas at El Paso 
ID: 
AddressLine1: 500 W University Ave
City: El Paso 
Country: United States
State: Texas
Zipcode: 79968
Latitude: 31.773088
Longitude: -106.505730

