LongName: University of Connecticut Storrs HPC Cluster
Description: Storrs Campus Research Cluster
ID: 10280
AddressLine1: 196A Auditorium Road U-3138
City: Storrs
Country: United States
State: Connecticut
Zipcode: "06269-3138"
Latitude: 41.8084
Longitude: -72.2495
