LongName: Boise State University 
Description: Boise State University 
AddressLine1: 1910 W University Dr
City: Boise 
Country: United States
State: Idaho
Zipcode: 83725
Latitude: 43.6037
Longitude: -116.2048
