LongName: Compute Canada Fir Cluster
Description: Fir is a versatile, heterogeneous computing cluster built in partnership with Lenovo Canada and Data Direct Networks (DDN) and is designed to support a wide range of scientific computations. It is hosted at Simon Fraser University (SFU).
AddressLine1: 8888 University Drive
City: Burnaby
Country: Canada
State: BC
Zipcode: "V5A 1S66"
Latitude: 49.278639393188136
Longitude: -122.91726450229353
