LongName: Saint Louis University 
Description: Saint Louis University 
ID: 
AddressLine1: 1 N Grand Blvd
City: St. Louis
Country: United States
State: Missouri
Zipcode: 63103
Latitude: 38.6456
Longitude: 90.2382

