LongName: University of Connecticut Physics OSG Cluster
Description: University of Connecticut at Storrs
ID: 10109
AddressLine1: 196A Auditorium Road U-3046
City: Storrs
Country: United States
State: Connecticut
Zipcode: "06269-3046"
Latitude: 41.8084
Longitude: -72.2495
